更多内容查看[这里](https://docs.scipy.org/doc/numpy/reference/routines.random.html)


## Simple random data | 常用随机函数

In [1]:
import numpy as np

### rand(d0, d1, …, dn)

In [2]:
# rand(d0, d1, …, dn)
# random values in a given shape
np.random.rand(1)

array([0.97299322])

In [3]:
np.random.rand(3, 4)

array([[0.81969546, 0.63076449, 0.70050141, 0.28701361],
       [0.5909755 , 0.10265285, 0.03841936, 0.04747027],
       [0.50586629, 0.33692611, 0.18006999, 0.37508064]])

In [4]:
np.random.rand(5)

array([0.4027442 , 0.29275407, 0.15175853, 0.76296697, 0.84970737])

### 正态分布随机数 randn(d0, d1, …, dn)

In [5]:
# randn(d0, d1, …, dn)
# return a sample or samples from standard norma sidtribution
np.random.randn(1)

array([0.68010349])

In [6]:
np.random.randn(4)

array([-0.22561174, -0.12611506,  1.42778485,  0.69267162])

In [7]:
np.random.randn(2, 2)

array([[ 1.09486998, -0.12217683],
       [-0.26184258,  0.70775913]])

*Note: We can use matplotlib to show the distrubution*

### 随机整数 

randint(low[, high, size, dtype]) / np.random.random_integers(2)

In [8]:
# randint(low[, high, size, dtype])
# return random integers from low(inclusive) to high(exclusive)
np.random.randint(1)

0

In [9]:
np.random.randint(3)

2

In [10]:
np.random.randint(100, 1000)

945

In [11]:
np.random.randint(0, 100, 5)

array([76, 86, 29, 40, 76])

In [12]:
np.random.randint(0, 100, (3, 3))

array([[88, 50, 90],
       [64, 69, 57],
       [ 2, 10, 95]])

In [13]:
# random_integers(low[, high, size])
# random integers of type np.int between low and high, inclusive
np.random.random_integers(2)

# This function is deprecated. Please call randint(l, r + 1) instead

D:\Anaconda3\Anaconda3_py36\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 2 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until


1

### 随机小数

* random_sample([size]) 
* random([size])
* ranf([size])
* sample([size])


In [14]:
# random_sample([size])
# return random floats in the half-open interval[0.0, 1.0)
np.random.random_sample(1)

array([0.42922028])

In [15]:
np.random.random_sample((3,3))

array([[0.13911191, 0.29153576, 0.38330187],
       [0.39095818, 0.37114282, 0.69224038],
       [0.3664121 , 0.02533538, 0.76235701]])

In [16]:
# random([size])
# return random floats in the half-open interval[0.0, 1.0)
np.random.random(1)

array([0.57758511])

In [17]:
np.random.random((2, 2))

array([[0.89365816, 0.10505705],
       [0.76704421, 0.27889437]])

In [18]:
# ranf([size])
# return random floats int the half-open interval [0.0, 1.0)
np.random.ranf(1)

array([0.64518204])

In [19]:
np.random.ranf((3,4))

array([[0.10753966, 0.70902024, 0.63834775, 0.65623879],
       [0.71709776, 0.34437971, 0.42639926, 0.70715686],
       [0.12977266, 0.20338805, 0.94316098, 0.3082274 ]])

In [20]:
# sample([size])
# return random floats int the half-open interval [0.0, 1.0)
np.random.sample(2)

array([0.95896772, 0.64870791])

In [21]:
np.random.sample((2, 2))

array([[0.91634732, 0.95899658],
       [0.59189998, 0.53045256]])

### 自定义随机

* choice(a[, size, replace, p])


In [22]:
# choice(a[, size, replace, p])
# generate a random sample from a given 1-D array
np.random.choice([3, 2, 1, 0],3)

array([3, 1, 3])

In [23]:
np.random.choice([3, 2, 1, 0],3, replace=False)

array([1, 2, 3])

In [24]:
np.random.choice(["cat", "dog", "fish", "mouse", "bird"],(2, 2), replace=True)

array([['cat', 'dog'],
       ['bird', 'dog']], dtype='<U5')

In [25]:
# p represents properties of the elements of the 1-D array
# sum of p must be 1.0
np.random.choice(["cat", "dog", "fish", "mouse", "bird"],(2, 2), replace=True,
                p=[0.1, 0.5, 0.3, 0.05, 0.05])

array([['fish', 'dog'],
       ['dog', 'fish']], dtype='<U5')

In [26]:
# bytes(length)
# return random bytes
np.random.bytes(1)

b'\x8c'

## Permutations | 排列

* shuffle(x)
* permutation(x)

In [27]:
# shuffle(x)
# modify a sequence in-place by shuffling its contents
# 将序列在原地打乱
x = np.arange(11)
print('----befor shuffle x----')
print(x)
print('----after shuffle x----')
np.random.shuffle(x)
print(x)

----befor shuffle x----
[ 0  1  2  3  4  5  6  7  8  9 10]
----after shuffle x----
[ 8  1  5  4  0  2  3  9  7  6 10]


In [28]:
# permutation(x)
# randomly permute a sequence, or return a permuted range
x = np.arange(11)
print("---permutation----")
print(np.random.permutation(x))
print("---x----")
print(x)

---permutation----
[ 9  4  6  0  5 10  8  3  7  2  1]
---x----
[ 0  1  2  3  4  5  6  7  8  9 10]


## Random generator | 随机数生成器

如果设置了seed，每次重新运行时生成的随机数都是确定和上次相同的。

In [29]:
# RandomState([seed])
# container for the Mersenne Twister pseudo-random number generator
np.random.RandomState(1)
np.random.random(5)

array([0.58048047, 0.57948883, 0.82388234, 0.77501925, 0.70183176])

In [30]:
# seed([seed])
# seed the generator
np.random.seed(0)
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [31]:
# get_state()
# return a tuple representing the internal state of the generator 
# np.random.get_state()

# set_state(state)
# set the interna state of the generator from a tuple